### PR TITLE
Make ExtensionComponent process nested components

### LINKED ISSUE #126: The ExtensionComponent does not process nested components
### Issue Type
bug report

#### Steps to Reproduce
Use the example app from the repo
1. Open the textBox
2. Modify the validation example:
```html
<TextBox valueChangeEvent="input" defaultValue={"required text"}>
    <Validator>
        <ValidationRule type="required" message="this is required" />
    </Validator>
</TextBox>
```
3. Start the app

#### Current Behavior
Validator is not bound to the TextBox

#### Expected Behavior
Validator is bound to the TextBox

### Environment Details
v18.1.4-alpha.7

### PR DESCRIPTION
**Pull request by IlyaKhD**
Fixes #126

### CODE REVIEW

File: src/core/component.ts [hunk 1]
```diff
@@ -111,7 +111,9 @@ abstract class ComponentBase<P> extends React.PureComponent<P, IState> {
     }
   }
 
-  protected abstract _preprocessChild(component: React.ReactElement<any>): React.ReactElement<any>;
+  protected _preprocessChild(component: React.ReactElement<any>): React.ReactElement<any> {
```
Comment (lukyanovas) [inline src/core/component.ts]: Should ComponentBase stay abstract after these changes?
