### PR TITLE
Make templates async

### LINKED ISSUE #151: Toolbar with itemComponent incorrectly render second item.
### Issue Type

bug report
### Description

The issue is related to Toolbar

#### Steps to Reproduce

See demo to reproduce.
#### Current Behavior
Second widget rendered with collapsed width.
#### Expected Behavior
Second widget will be rendered with width like first widget. 
#### Demo

https://stackblitz.com/edit/devextreme-react-b9ljgy?file=index.js
### Environment Details

- devextreme version: "^18.1.3
- devextreme-react version:  "^18.1.4-alpha.7"
- react version: "^16.4.1"

### LINKED ISSUE #153: Inner components aren't rendered when they are configured with the template
### Issue Type
bug report

### Description
The issue may be related to https://github.com/DevExpress/devextreme-react/issues/151

#### Current Behavior
1. The menu isn't visible by default
2. The menu has one rendered item

#### Expected Behavior
1. The menu is visible by default
2. The menu has two rendered items 
#### Demo
https://stackblitz.com/edit/devextreme-react-r5m6tj?file=index.js

### LINKED ISSUE #163: The "E1010 - The template does not contain the TextBox widget" error occurs if value is assigned to the TextBox.fieldComponent or TextBox.fieldRender property
### Issue Type
bug report

#### Steps to Reproduce
The "E1010 - The template does not contain the TextBox widget" error occurs if value is assigned to the TextBox.fieldComponent or TextBox.fieldRender property

```js
class Example extends React.Component {
  render() {
    return (
      <SelectBox
        fieldRender={()=>{
          alert(123);
          return (<TextBox value="123"/>);
        }}
      >
      </SelectBox>
    );
  }
}
```
#### Demo
https://stackblitz.com/edit/devextreme-react-selectbox-fieldrender?file=index.js

### PR DESCRIPTION
**Pull request by lukyanovas**
Fix #153, fix #163, fix #151 
devextreme v18.1.5 version is nessesary

depends on https://github.com/DevExpress/DevExtreme/pull/4853

### CODE REVIEW

File: src/core/template-wrapper.ts [hunk 1]
```diff
@@ -18,6 +19,14 @@ class TemplateWrapper extends React.PureComponent<ITemplateWrapperProps, object>
     }
 
     public componentDidMount() {
+        if (this.props.onRendered) {
+            setTimeout(() => {
+                if (this.props.onRendered) {
```
Comment (IlyaKhD) [inline src/core/template-wrapper.ts]: Is this double-check required? I believe one can be omitted

Comment (lukyanovas) [reply src/core/template-wrapper.ts]: The second check is related with TS compilation
